//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.SpeakRecordGoolge {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpeakRecordGoolge.ISpeakRecord", CallbackContract=typeof(ConsoleApp2.SpeakRecordGoolge.ISpeakRecordCallback))]
    public interface ISpeakRecord {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpeakRecord/StartRecord")]
        void StartRecord(int postPause);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpeakRecord/StartRecord")]
        System.Threading.Tasks.Task StartRecordAsync(int postPause);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpeakRecord/StopRecord")]
        void StopRecord();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpeakRecord/StopRecord")]
        System.Threading.Tasks.Task StopRecordAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpeakRecordCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISpeakRecord/TranscriptContract")]
        void TranscriptContract(string textTranscrip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpeakRecordChannel : ConsoleApp2.SpeakRecordGoolge.ISpeakRecord, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpeakRecordClient : System.ServiceModel.DuplexClientBase<ConsoleApp2.SpeakRecordGoolge.ISpeakRecord>, ConsoleApp2.SpeakRecordGoolge.ISpeakRecord {
        
        public SpeakRecordClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SpeakRecordClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SpeakRecordClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SpeakRecordClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SpeakRecordClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void StartRecord(int postPause) {
            base.Channel.StartRecord(postPause);
        }
        
        public System.Threading.Tasks.Task StartRecordAsync(int postPause) {
            return base.Channel.StartRecordAsync(postPause);
        }
        
        public void StopRecord() {
            base.Channel.StopRecord();
        }
        
        public System.Threading.Tasks.Task StopRecordAsync() {
            return base.Channel.StopRecordAsync();
        }
    }
}
